### PR TITLE
Catch exceptions when resolving macros in rc.conf

### PR DESCRIPTION
**Pull request by toonn**
While parsing the settings in `rc.conf` `self.fm.thisfile` doesn't exist
yet.

### CODE REVIEW

**Comment by cibinmathew** [comment]
There are few more I could see further down which raises exception while resolving macros.

**Comment by cibinmathew** [comment]
@toonn can you please review the other scenarios also added.

**Comment by toonn** [comment]
@cibinmathew I dove in and implemented what I think is necessary to ease my concerns. Much less duplication and I believe I've retained the semantics re `None`.
It'd be great if you could test this branch.

**Comment by vifon** [comment]
@toonn Looks good to me. Resolve the conflicts and I think it's good to go.

**Pull request merged**
