### PR TITLE
Add a snap

### PR DESCRIPTION
**Pull request by evandandrea**
#### ISSUE TYPE

- Improvement/feature implementation

#### CHECKLIST
- [x] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [x] All changes follow the code style **[REQUIRED]**
- [x] All new and existing tests pass **[REQUIRED]**
- [ ] Changes require config files to be updated
    - [ ] Config files have been updated
- [x] Changes require documentation to be updated
    - [ ] Documentation has been updated
- [ ] Changes require tests to be updated
    - [ ] Tests have been updated

#### DESCRIPTION

It's currently hard to get an up to date version of Ranger on older versions of Ubuntu. 16.04 is at 1.7.1.

#### MOTIVATION AND CONTEXT

I've taken a bit of time to put a snap together (I work on Snapcraft) so ranger can be installed and upgraded from any version of Ubuntu, or one of many other distros (also version independent). As the Snap Store is [browsed](https://snapcraft.io/store) by millions, it'll also have the bonus of getting some more eyeballs on ranger.

#### TESTING

To build it, `snap install snapcraft` from Ubuntu, or [install Multipass](https://github.com/CanonicalLtd/multipass/releases) on MacOS then `brew install snapcraft`. Then run `snapcraft` to create the .snap file.

To publish, [create an account](https://snapcraft.io/account), then:
```
snapcraft login
snapcraft register ranger
snapcraft push --release=stable *.snap
```

### CODE REVIEW

**Comment by toonn** [comment]
It shouldn't be too hard actually, clone the repository then `make && make install` should be all you need. Ranger's also in nixpkgs so you could use nix to get it on ubuntu or any other supported platform. Brew also has support for both the latest stable release *and* `HEAD`.

Note that I'm not against adding a snap to snapcraft but I did label this with needs-opinions because we don't keep the nixpkgs expression in tree, nor the debian, arch, whatever packages. The closest thing is support for PyPI in our `Makefile` afaik. So we need to discuss how we want to deal with this.

**Comment by Vifon** [comment]
@evandandrea Are the snaps usually maintained by the upstream or rather by the external maintainers (like with the regular repos)? I don't think any us use snaps regularly so I wouldn't count on us testing it properly internally.

**Comment by evandandrea** [comment]
@Vifon they're typically maintained by the upstream to ensure users can trust and find support for what they install. I think it's also beneficial to you as publisher, as it'll give you install base metrics (anonymized) and we can help with [promotion](https://blog.ubuntu.com/2018/11/29/gitkraken-picks-up-community-demand-to-adopt-snaps).

**Comment by toonn** [comment]
We're not all that interested in maintaining packaging. We only do it for PyPI. Why can debian/arch/nixos/and others maintain their own packages but not snapcraft? It'd be great if someone in the community assumes the mantle but like the others, it's not going in the main repo.

**Comment by Vifon** [comment]
The main problem is that we'd need to have Snap installed to maintain the package and I don't think we have any interest in it as the users of our systems. Of course a VM would work too but it's an additional step. I'd be fine with a community-supported package.

**Comment by toonn** [comment]
Closing this because of a lack of interest on our part. We would definitely point to a snap for ranger from the readme if it's maintained by someone interested in doing so.

**Pull request closed without merging**
