### PR TITLE
Improving view commands

### PR DESCRIPTION
**Pull request by mrgoodvin**
Improving view descriptions of commands and command groups

#### ISSUE TYPE

- Improvement/feature implementation

#### RUNTIME ENVIRONMENT

- Operating system and version: no matter
- Terminal emulator and version: no matter
- Python version: 
- Ranger version/commit: 
- Locale: no matter

#### CHECKLIST

- [X] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [X] All changes follow the code style **[REQUIRED]**
- [X] All new and existing tests pass **[REQUIRED]**
- [X] Changes require config files to be updated
    - [X] Config files have been updated
- [X] Changes require documentation to be updated
    - [ ] Documentation has been updated
- [X] Changes require tests to be updated
    - [ ] Tests have been updated

#### DESCRIPTION

desctiption of hotkeys is sefed in rc.conf file optional.
Instead of '...' appear list commands by default.
syntax:
map KEY [chain echo YOUR_NAME_GROUP_COMMAND::[YOUR_NAME_COMMAND];] commands
where commands is/are comand1[; command2][; ...commandN]

#### MOTIVATION AND CONTEXT

it is nice :). If are many keys will be may to do input hot-keys easy

grouping hot keys in thematics

#### IMAGES / VIDEOS

https://i.ibb.co/2hq1CSY/ranger-view-commands.png
https://i.ibb.co/6F6mfWP/ranger-view-commands-more.png
https://i.ibb.co/6HLFkYK/ranger-view-commands-more-and.png

### CODE REVIEW

**Comment by toonn** [comment]
I like this idea but not the implementation. It's already possible by writing custom commands in `commands.py` in principle. But a lightweight way to define new commands from `rc.conf` if they are just sequences of existing commands would be cool.

**Comment by mrgoodvin** [comment]
Yes, I agree. Later maybe will be done.

**Comment by toonn** [comment]
I think you misunderstood me. What I don't like is `chain echo SOMENAME; command`. I'd like something like `named SOMENAME command` which would act like defining a new command class in `commands.py`, a very simple one of course. And in the UI we'd display `SOMENAME` rather than `some long and maybe confusing command`.

**Comment by mrgoodvin** [comment]
Yea, I understand now. Agree at all 100 :)

**Comment by mrgoodvin** [comment]
Good idea if make description for command and command group. It give choice to users of next combination on hotkey:
• save command description in log
• do not save command description in log
• view command description in status-bar

**Pull request closed without merging**
