### PR TITLE
dirname_in_tabs setting can be changed from ranger

### PR DESCRIPTION
**Pull request by hektr**
dirname_in_tabs setting can be changed from ranger using `zt`

### CODE REVIEW

**Comment by toonn** [comment]
This is a fine key binding if you do this often but I think most people will prefer either having it on or having it off so I don't see a good reason to provide this by default. Feel free to try to change my mind though.

**Comment by hektr** [comment]
@toonn, yes, you are right. But this option is popular. A lot of people will try to enable it. It's more easy and fast to do using zt than by editing config file, especially for new users.

**Comment by toonn** [comment]
Sure but it's not permanent. Key bindings to toggle settings are more for things you might often want to change on an open ranger instance.

**Comment by hektr** [comment]
@toonn, thanks :) in this case, you are right

**Pull request closed without merging**
