### PR TITLE
xdg: Add support for XDG_DATA_HOME

### LINKED ISSUE #303: bookmarks, tags and history should be in XDG_DATA_DIR or ~/.local/share/ranger

### PR DESCRIPTION
**Pull request by genkimarshall**
I think this is all. It didn't seem like any docs needed to be updated (?).
Also, not sure about the `_relpath` factoring out.
Resolves #303.

### CODE REVIEW

**Comment by hut** [comment]
Sounds like the right thing to do, but what about the 10k confused console cowboys who will wonder where their important bookmarks and tags went?

**Comment by genkimarshall** [comment]
I was wondering about that. Is there any precedence of this sort of
breaking-change for ranger?

Here are some not-ideal, but possible thoughts at least for discussion...
- Wait until hypothetical 2.0.0 and document it as something you must
  handle.
- Detect: If history/tags/bookmarks are in the old location, print to the
  console saying this is deprecated. Then it can perhaps continue to
  use those until the user moves them over to XDG_CONFIG_HOME location.
- Or instead, it could exit with error, explaining that you must move them.
- It could perhaps be another command-line / env-var option, but...

Perhaps this sort of change is simply not worth it. In that case this PR
and the issue can simply be closed.

**Comment by hut** [comment]
Using ~/.config/ranger/{tagged,bookmarks,history} if they exist, and ~/.local/share/ranger/* if they don't, sound like the most sensible way to handle this. In time, most users will have their data in ~/.local/share/ranger.

**Comment by hut** [comment]
Oh, don't forget to place `~/.config/ranger/copy_buffer` file in `$XDG_DATA_HOME` too, in case it isn't yet.  It's used in the `:save_copy_buffer` and `:load_copy_buffer` commands which transfer yanked files to different ranger instances.

**Comment by genkimarshall** [comment]
Quoting hut (2016-01-31 14:35:11)
> Oh, don't forget to place `~/.config/ranger/copy_buffer` file in
> `$XDG_DATA_HOME` too, in case it isn't yet.  It's used in the
> `:save_copy_buffer` and `:load_copy_buffer` commands which transfer
> yanked files to different ranger instances.

Thanks for the help/feedback. Unfortunately, school has just started and
because I'm currently sitting on a fresh install and not using ranger ATM,
I'm not finding enough motivation to finish this off right away. So if
anyone reading this wants to, please go ahead. Otherwise, I will get to
this sometime in the future.

**Comment by soredake** [comment]
any updates?

**Comment by nfnty** [comment]
Rebase this PR and make sure that all tests pass. See the updated `CONTRIBUTING` and `HACKING` documents for more info. Thanks!

**Comment by genkimarshall** [comment]
@nfnty I think @hut makes good points in his last two comments. But, this PR doesn't implement those items yet.

I don't think I'm going to make progress on this in the near future. So to anyone: Please feel free to use this work in a new PR.

**Pull request closed without merging**
