### PR TITLE
Implement image previewing for archive files

### PR DESCRIPTION
**Pull request by jakanaka-evan**
#### ISSUE TYPE

- Improvement/feature implementation

#### CHECKLIST

- [X] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [X] All changes follow the code style **[REQUIRED]**
- [X] All new and existing tests pass **[REQUIRED]**
- [ ] Changes require config files to be updated
    - [X] Config files have been updated
- [ ] Changes require documentation to be updated
    - [ ] Documentation has been updated
- [ ] Changes require tests to be updated
    - [ ] Tests have been updated

#### DESCRIPTION

Implemented archive previews in scope.sh. It uses the first alphabetically
sorted image file in the archive or falls back to text-based preview methods if
there are none.

### CODE REVIEW

**Comment by toonn** [comment]
Hmm, interesting. What archive formats does it support? And what are the optional deps?

Could be nice for comic book previews for example.

**Comment by jakanaka-evan** [comment]
For now it only supports `.rar` and `.zip` files. Opt-deps are
 - for `.rar` files: `unrar OR bsdtar`,
 - for `.zip` files: `zipinfo (from unzip) AND atool OR bsdtar`.
I'll try to add `.7z`, `.tar`, and `.cbz`support today, and look into removing
the `atool` dep for `.zip` files.

`atool --list` is unfortunately not very suitable for this, since it lists
files differently for different formats.

**Comment by toonn** [comment]
Don't forget `.cbr`, that's still popular for comics. `.tar.gz & .tar.bz2` would be nice, oh and `.xz`.

**Comment by jakanaka-evan** [comment]
Here we go, added support for all of the requested formats and removed the `atool` dependency.
See jakanaka-evan/ranger@8fd92581dfcd126ce432b8832209f8cdf4a73ecd for more information on optional dependencies.

**Comment by toonn** [comment]
Hmm, one more suggestion. Can you check mimetype  instead of using just the extension to determine something's a picture? Maybe not if you only get the filename. The python mimetypes module does mimetype by extension but maybe running python just for that is overkill.

Let's add at least `tiff, bmp and webp` though.

**Comment by jakanaka-evan** [comment]
Changed `grep` into a `python -c "import mimetypes as m; ..."` command. It
obviously performs slower than a grep, but we are listing archive contents
prior to that anyway, so relatively speaking it's not that worse I think.

**Comment by jakanaka-evan** [comment]
I've fixed up everything I could think of and made it pass shellcheck, so i
think it's ready for merge now.

**Comment by Vifon** [comment]
It needs a comment describing what it is actually doing (i.e. previewing the first file in an archive). Apart from, if it works for you, @toonn, merge away!

**Comment by toonn** [comment]
🎉 Thanks for the contribution!

**Pull request merged**
