### PR TITLE
Cleanup the urxvt image previews

### PR DESCRIPTION
**Pull request by Vifon**
A cleanup of the new urxvt-based image previews. Depends on #682 and #687.

### CODE REVIEW

**Comment by ssh0** [comment]
@Vifon L312 and L313 may be miss.

**Comment by Vifon** [comment]
Ugh... I think I've broken the escape codes in the last minute of this "cleanup"... In more than one way! I missed `self.` and I've screwed up the escape codes. Let me just...

**Comment by Vifon** [comment]
...or not. Let's leave the history alone... Should be fixed now, I've tested it.

**Comment by nfnty** [comment]
Is this ready for merging?

Rebase this PR and make sure that all tests pass.

**Comment by Vifon** [comment]
It's ready for merging and/or review.

**Comment by nfnty** [comment]
Does this fix any open issues?

**Comment by Vifon** [comment]
No, only the ones mentioned in the original description (which are closed).

**Pull request merged**
