### PR TITLE
Vcs hg improvements

### PR DESCRIPTION
**Pull request by charignon**
This series of patches improves the reliability + performance of the support for mercurial.
I tested the series of patches on the hg core repository.

### CODE REVIEW

**Comment by nfnty** [comment]
Please, try PR #408 and report back.

**Comment by charignon** [comment]
The series is 52 commits, it is too complex to review as one pull request, have you thought about doing it more iteratively?
Anyway, if your series is ready it should probably go in as-is and you can ping me when it is pushed to reword the mercurial-specific bits.

**Comment by hut** [comment]
#408 is now merged, give it another shot :)

**Comment by nfnty** [comment]
Fixed in `master`.

**Pull request closed without merging**
