### PR TITLE
Fix ranger freeze after shell command during kitty preview

### PR DESCRIPTION
**Pull request by Nfanja**
#### ISSUE TYPE

- Bug fix

#### RUNTIME ENVIRONMENT

- Operating system and version: Arch Linux x86_64
- Terminal emulator and version: kitty 0.14.6
- Python version: Python 3.8.0
- Ranger version/commit: 1.9.2.389.g28f3d014-1
- Locale: en_US.UTF-8

#### CHECKLIST

- [x] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [x] All changes follow the code style **[REQUIRED]**
- [x] All new and existing tests pass **[REQUIRED]**
- [ ] Changes require config files to be updated
    - [ ] Config files have been updated
- [ ] Changes require documentation to be updated
    - [ ] Documentation has been updated
- [ ] Changes require tests to be updated
    - [ ] Tests have been updated

#### DESCRIPTION

preview_id was assigned negative id, which is not valid kitty id

#### MOTIVATION AND CONTEXT

#1603

### CODE REVIEW

**Comment by Nfanja** [comment]
Indeed, max should be there, somehow it was lost :)

**Comment by GermainZ** [comment]
This should probably be `self.image_id = max(0, self.image_id - 1)` (note the `- 1`), otherwise it causes ranger to freeze on quit.

**Comment by Yutsuten** [comment]
Lately I'm frequently being affected by this freeze...
Wanted the fix so bad that didn't care fixing it myself... But there was a fix here, many thanks.

```diff
-self.image_id -= 1
+self.image_id = max(0, self.image_id - 1)
```

No more freezes so far.
Hope this gets fixed upstream soon.

**Review by toonn — COMMENTED** [review]
You dropped the decrement when you added the max : )

**Comment by mmrzax** [comment]
ranger `1.9.3-9` (pacman)
Same problem 
After checking the `img_display.py` , I realized that these changes have not been applied after three years. Just as a question: which branch is in the Arch repository?

**Pull request merged**
