### PR TITLE
Replace assert

### PR DESCRIPTION
**Pull request by frankm42**
This is a first attempt to replace the use of assert (outside of tests) in ranger.
Fixing https://github.com/ranger/ranger/issues/1514

Any comments/improvements?

### CODE REVIEW

**Comment by toonn** [comment]
Hmm, shouldn't failing asserts result in exceptions rather than fairly silent failure?

**Comment by frankm42** [comment]
Yes it should, however I am not quite sure about the best way to do this.
Maybe someone with actual experience in python can show the way.

**Comment by frankm42** [comment]
This is not the correct fix.
If someone tells shows the way, I am willing to fix it right on all areas where ranger uses assert

**Comment by toonn** [comment]
I think the only way is to figure out what errors will happen when the asserts fail and then catch and handle those in the correct way. Keeping in mind that some asserts may check boolean equations which would be replaced with if-statements.

**Comment by toonn** [comment]
Next time feel free to keep pushing/force pushing to the same branch, no need to close the PR, any and all history attached to decisions can be valuable.

**Pull request closed without merging**
