### PR TITLE
Add Space and navigation keys to the cheatsheet

### PR DESCRIPTION
**Pull request by Sighery**
#### ISSUE TYPE

- Improvement/feature implementation

#### RUNTIME ENVIRONMENT

Not applicable

#### CHECKLIST

- [X] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [ ] All changes follow the code style **[REQUIRED]**
- [ ] All new and existing tests pass **[REQUIRED]**
- [ ] Changes require config files to be updated
    - [ ] Config files have been updated
- [ ] Changes require documentation to be updated
    - [ ] Documentation has been updated
- [ ] Changes require tests to be updated
    - [ ] Tests have been updated

I've read the contributing guide. I believe code style and tests do not apply to this change, since I'm just modifying the cheatsheet `svg` file.

#### DESCRIPTION

Added a new row on the Cheatsheet to list some functionality from the navigation keys. I was mostly interested in adding in Space that is used to toggle mark, and Insert, that is used for `:touch`. However, since I was at it I made sure to document the default mapping of Home, End, Page Up and Page Down (Delete is currently not used).

I've also made a few small aesthetic changes, moving some texts a few pixels around or making some boxes a few pixels bigger when possible, since some already existing boxes were crowded and text would overflow.

Another change to note is that apparently since the time and version of Inkscape this `svg` was made, Inkscape has changed its default DPI from 90 (which was used in this file) to 96. [More info can be found here](http://wiki.inkscape.org/wiki/index.php/Release_notes/0.92#Important_changes). I'm not really that knowledgeable on design stuff, like DPI, or Inkscape, but it prompted me to update it to be able to work with it so I did. Nothing seems to have broken, as far as I can see.

#### MOTIVATION AND CONTEXT

I'm still a newbie to Ranger, recently installed Manjaro i3 and Ranger was included with it, which so far I'm loving. I searched around and found the cheatsheet which is extremely useful and I printed out to always have nearby to look at while I keep learning it. However, some other useful default commands like Space and Insert I found later on by Googling were not included. I don't know how widely used the cheatsheet is, but both mark and touch are useful commands and for any newbies like me it's useful to have them listed so I don't forget.

#### TESTING

This doesn't affect any part of the codebase, as far as I know.

#### IMAGES / VIDEOS

ranger-cheatsheet

### CODE REVIEW

**Comment by Sighery** [comment]
Sorry for that last rebase, noticed the text at the top, on the GitHub link and the IRC channel was clipping so I did a quick rebase to fix it. Also updated the PNG on the MR description with the change.

**Comment by Sighery** [comment]
Wasn't it already included with the previous cheatsheet? On the _Shift_ row, at the end, there's `?` highlighted in red. Not sure if that's what you mention :thinking:

**Comment by toonn** [comment]
Ah, indeed. Couldn't find it. Could you make it the same orange other unfinished commands have? And mention it can list keybindings and command documentation.

**Comment by Sighery** [comment]
Sure, sounds like a good idea. I can make it orange and add a reference to it like on some other commands such as `c`, and then document it on the box below as `(6)`. I'll see how I can add the extra text in without breaking the layout.

**Comment by Sighery** [comment]
Documented that `?` opens up some other key bindings you can press to get more information on stuff. Let me know if you wanted something else.

ranger-cheatsheet

**Comment by Sighery** [comment]
Hmmm... I'm just noticing that for some reason on Brave (Chromium based) some boxes are rendered bigger than they appear on Inkscape or Firefox. Currently looking into it. It might have to do with the migration from 0.91 Inkscape to 0.92, where it prompted me to change the DPI.

2019-10-12-004041_718x846_scrot

I'd ask for some extra time until then, not sure if it's possible to mark a PR as WIP in GitHub, to see what's going on with that weird rendering. Also recently found out that inkscape embeds some information into the svg itself, like if you export the SVG to a PNG, where is it exported to, which I'd also like to remove since it adds nothing. I'll probably end up doing a rebase of the whole branch so it ends up with a clean history, since chances are I'll have to downgrade to Inkscape 0.91 and re-do all the changes again anyway.

**Comment by toonn** [comment]
Np, we're glad the cheatsheet's getting some love : )

**Comment by Sighery** [comment]
Sorry, life got busy lately, started at a new job and had some work trips and completely forgot about this.

I've checked on Windows/Chrome, and the current cheatsheet on master has the same issue I posted up above. Meanwhile, on my Manjaro/Brave the cheatsheet on master does not. And this PR's version does. But this PR's version with Manjaro/Firefox doesn't.

I tried downgrading back to v0.91. Tried with both Windows10 and Manjaro. Both would end up with the same issue once saved, but it would only show up in certain setups, so not quite sure what's going on or how to fix it, or what causes it to just be an issue in certain setups.

So for now I've just rebased my fork to be up to date with `ranger:master`. The extra space bothers me but I don't think I can do much about it. Maybe you can try and see if it's an issue with your setup.

**Pull request merged**
