### PR TITLE
added support for DJVU text conversion

### PR DESCRIPTION
**Pull request by chakravala**
provides the ability to preview DJVU files with text preview, just like PDF files

#### ISSUE TYPE
- Improvement/feature implementation

#### RUNTIME ENVIRONMENT
Requires `djvutxt` program provided by `djvulibre` to convert

#### CHECKLIST
- [X] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [X] All changes follow the code style **[REQUIRED]**
- [X] All new and existing tests pass **[REQUIRED]**
- [X] Changes require config files to be updated
    - [x] Config files have been updated
- [ ] Changes require documentation to be updated
    - [ ] Documentation has been updated
- [ ] Changes require tests to be updated
    - [ ] Tests have been updated

#### DESCRIPTION
Very simple implementation on `scope.sh` that provides the ability to preview DJVU files with text preview, just like PDF files, only requires `djvutxt` to be installed on system

#### MOTIVATION AND CONTEXT
These changes help with previewing DJVU files with text conversion, so that they can be previewed just like PDF documents. This solves the problem of not having a text preview of DJVU files

#### TESTING
No tests have been run, as this doesn't affect any of the existing code base.

### CODE REVIEW

**Comment by toonn** [comment]
Could you add wrapping with `fmt` as is done for pdf previews? I think it's better to stay consistent.

**Comment by chakravala** [comment]
Yes, I inserted it now. I made this modification many months ago, before `fmt` was added to the PDF.

**Comment by ertwro** [comment]
Hi. It's working quite well but by any chances could you also add support for images? I remember you could do something like this:
ddjvu -page=1 -format=tiff "$filename" "${outputdir//.tif}" && convert "${ouputdir//.tif}" -quality 10 "${outputdir//.jpg}"

**Comment by toonn** [comment]
That's in the works still at #1421.

**Pull request merged**
