### PR TITLE
Add support for default terminal word-movement commands to console

### PR DESCRIPTION
**Pull request by Zaeph**
#### ISSUE TYPE

- Improvement/feature implementation

#### RUNTIME ENVIRONMENT

- Operating system and version: Arch Linux x86_64
- Terminal emulator and version: terminator 1.91
- Python version: 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
- Ranger version/commit: ranger-master 1.9.1
- Locale: En/GB

#### CHECKLIST

- [X] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [X] All changes follow the code style **[REQUIRED]**
- [X] All new and existing tests pass **[REQUIRED]**
- [X] Changes require config files to be updated
    - [X] Config files have been updated
- [x] Changes require documentation to be updated
    - [x] Documentation has been updated
- [ ] Changes require tests to be updated
    - [ ] Tests have been updated

#### DESCRIPTION

Adds the following key bindings in the console:
- Alt-b for moving backwards by words,
- Alt-f for moving forwards by words.

#### MOTIVATION AND CONTEXT

I found myself intuitively using those key bindings when composing commands. The following lines were present in `rc.conf`:
```conf
cmap <a-left>   eval fm.ui.console.move_word(left=1)
cmap <a-right>  eval fm.ui.console.move_word(right=1)
```
Sadly, those key bindings didn't work in my terminal (`terminator`), so I added the alternatives I expected to `rc.conf`. I took the liberty of not adding the original key bindings to the `man` pages, since they didn't work on my end, but if they do work on someone else's, it'll be trivial to edit the `man` page.

(Also, this is the first pull request I ever make, so excuse me if I've done anything wrong, and please bear with me whilst I figure out the ins and outs.)

### CODE REVIEW

**Comment by Zaeph** [comment]
You’re right about the punctuation. I just skimmed up and down a bit in the manual and noticed that there were irregularities. We could just drop this commit altogether for the moment.

**Comment by toonn** [comment]
It's a great first PR though, keep 'em coming ; )

**Comment by Zaeph** [comment]
Thank you for your feedback. :)

I wasn't sure whether it warranted a pull request. Since the lines already present in `rc.conf` didn’t seem to do anything on my end, it felt somewhat vindicated.
However, as an Emacs user, I was going to suggest the following patch to enable the default way of cancelling commands in Emacs (`Ctrl-G`):
```diff
# And of course the emacs way
+copycmap <ESC>       <C-g>
copycmap <up>        <C-p>
copycmap <down>      <C-n>
...
```

I didn’t want to include a commit for this in this PR because I wasn’t sure whether `Ctrl-G` had a specific role which wouldn’t show up in `rc.conf`, but I could make a quick commit to this PR or open another if you feel this could be useful.

Although this is my first time opening a PR, it’s not my first time *considering* it, and I’d hate to clutter a project with trivial PRs whose additions could very well be useful to me alone.

**Comment by toonn** [comment]
You could open another PR for that. While the console has readline inspired keybindings, everything else is still very much inspired by vim. check `rc_emacs.conf` for the more emacs inspired bindings.
However, vim's `C-g` isn't very useful for the console imo so we might accept it anyway.

**Comment by Zaeph** [comment]
Hello,

I’m not sure if I’ve done the right thing—and I welcome your input if I haven’t—but I've pulled the merged changes from #1287 onto my forked `master` branch, and then rebased my changes on `patch-1` on top of it.
I wasn’t sure whether to *merge* or *rebase*, not knowing what the best practice would be, but I’ve eventually opted for the later. Please excuse me if I should have done otherwise.

**Comment by toonn** [comment]
@Vifon, do the arrow key bindings work for you?

**Comment by toonn** [comment]
Ok, so we've agreed this is good. Couple things though. We don't want to remove alt-lef/right from documentation. And can you use copycmap?

And could you look into further readline key bindings that are currently missing? Would make for some good usability improvements. I know that when I started using ranger I figured it wasn't possible to support most of them then I just got used to them being missing and just dealt with it, not even considering adding them.

**Comment by Zaeph** [comment]
Hello,

> Ok, so we've agreed this is good. Couple things though. We don't want to remove alt-lef/right from documentation. And can you use copycmap?

I’ve incorporated those changes in 5651108:
- Alt-B and Alt-F are set as the default bindings (cmap),
- Alt-LEFT and Alt-RIGHT are set as alternative bindings (copycmap).
Let me know if you’d rather have me do the reverse.

> And could you look into further readline key bindings that are currently missing? Would make for some good usability improvements. I know that when I started using ranger I figured it wasn't possible to support most of them then I just got used to them being missing and just dealt with it, not even considering adding them.

Based on my own experience there are a few features that I’d like to have in `ranger`’s console:
1. **Quick access to the last console command in history** from the main view (`Ctrl-p` in a regular terminal),
2. **Forward and reverse history search** (`Ctrl-s` and `Ctrl-r` in a regular terminal),
3. **Forward and reverse history search for a given string** (`Alt-s` and `Alt-r` in a regular terminal),
4. **Tab-completion** for programs when the point is not at the end of the input string.
  At the moment, pressing `@` enters the console with `:shell V %s` where `V` is the point, but entering the beginning of a command (i.e. `fe` for `feh`) and pressing `Tab` brings the point to the end of the line (`:shell fe %sV`) rather than expanding the argument at point. When the point is at the end of the line, the argument expands normally.

And here are some observations on those features:
- 2c3beb6 is an attempt to address 1. by mapping `Ctrl-p` in the main view to the console, allowing subsequent `Ctrl-p` to go backwards in history,
- It seems to me that 2. and 3. would require a patch that is beneath my current abilities. I’ve tried looking in the code for commands of the likes of `fm.ui.console.history_move` to see if it could lead me to something I could use, but it came to naught,
- For 4., it only seems to be a small bug that could easily be fixed, although it’s a bit daunting for me right now to jump in the code proper and address it, although I could try.

I think that the console is pretty usable as it is, and based on my own experience with the terminal, I don’t find myself needing anything more than the 4 aforementioned features.

Thank you for your feedback, and let me know if I can do anything else.

**Comment by toonn** [comment]
Noticed some changes to the man page due to a version change but I'm ignoring them, that file is regenerated all the time so it doesn't really matter either way, probably?

**Comment by Zaeph** [comment]
I noticed this too, and wasn't sure whether to discard the incriminating hunks in the file generated on my end by `pod2man`. In the end, I decided against it, but we can always do this later down the line if it caused unforeseen problems.

Still, thank you for the merge.

**Comment by Zaeph** [comment]
Hello again,

I’ve opened 2 new issues and added a comment on an older one:
- 1 → #1293,
- 2 & 3 → #1292,
- 4 #706.

I’ve made suggestions in the respective entries, and I’ll try to work on them to the best of my abilities.

As for finishing my first contribution, thank you again for assisting me. I’m just glad I could help.
I wish I could do more or fill my own feature requests, but I don’t know any Python and have only been delving in `emacs`’s Elisp to address my editing needs. I want my desire to contribute to be the driving force towards learning other languages and learning from seasoned developers here and elsewhere. In the meantime, all I can offer is my ability to tinker in a methodical fashion, and I’m glad if it’s of any use to the project.

**Comment by toonn** [comment]
No matter the skill level, there's always something to be done. Documentation can always use improvement and just identifying and reporting issues or triaging/reproducing existing issues are really helpful.

We also encourage anyone and everyone to try their hand at contributing code, we'll try to help as much as we can through comments and reviews and you can always hop into irc at #ranger@freenode for more realtime guidance/discussion (or just to talk about what bothers you about distro so-and-so or what cool new software you stumbled across ; ).

**Comment by Zaeph** [comment]
Hi,

Thanks for the recommendation. I'm just starting to get involved with the community, but I'll make sure to drop by the IRC, which is yet one more thing that I've never done. There's `ERC` for that in `emacs`, so I'll read get acquainted with the manual.

At any rate, thank you for guiding me through the process. This was more of an experiment than anything else, but you've given me enough reasons to keep contributing in the little ways I can, at least for the foreseeable future.

**Comment by toonn** [comment]
Yep, I used erc when chatting about Agda, was very nice to have access to agda-mode from inside the irc client. There's also circe for emacs.

**Comment by Zaeph** [comment]
That’s what I did, and I’ve got everything working. I’m planning on setting up a ZNC bouncer on an old laptop to keep up with messages, but I’m sensing a potential headache on that one.

**Comment by toonn** [comment]
You could check this out, it's a [free bouncer for freenode](https://firrre.com).

I don't personally use a bouncer, it's definitely not something you *need*. It may be something you *want* though.

**Comment by toonn** [comment]
Yes, dat fomo : ) I don't mind but then again I'm in the channel for 8+ hours a day so I don't miss all that much. The channel's pretty quiet when europe goes to sleep.

**Pull request merged**
