### PR TITLE
Switching between first/last tab

### PR DESCRIPTION
**Pull request by hektr**
Switching between first/last tab 

I tried to do a quest from here #1939 ! I don't know, whether I've done this correct or not. But at first glance it works.

I added keyword argument to tab_move function to make that function use offset as tab index(we don't need offset for going to the first/last tab, but we need index -- zero or -1).

So, we can now write at rc.conf something like:

`map gz tab_move -1 use_offset_as_index=yes`
and it will use -1 not as offset, but as index of tab. So, it switch to the last tab.

`ga` is used for switching to the first tab and `gz` for last. It's easy to remember, because `a` is the first letter of alphabet, and `z` is the last. And it's easy to type :)

### CODE REVIEW

**Comment by hektr** [comment]
Sory, first time it showed errors, because of keyword argument name(it was useOffsetAsTabIndex). Tests don't like varibales, writed on camelStyle.

**Comment by mrgoodvin** [comment]
Thanks. This version is better, imho. Might it be worth making the parameter / argument name shorter? (maybe — 'is_index'?). Who would like to remember such a long word combination?

**Comment by hektr** [comment]
> Thanks. This version is better, imho. Might it be worth making the parameter / argument name shorter? (maybe — 'is_index'?). Who would like to remember such a long word combination?

yes, you're right. It has one more disadvantage. I'll change it a liitle.

**Comment by toonn** [comment]
Hmm, looking more closely at the code I'm not sure we need this. If you specify a quantifier this already happens, for example `1gt` moves to the first tab.

**Comment by hektr** [comment]
> Hmm, looking more closely at the code I'm not sure we need this. If you specify a quantifier this already happens, for example `1gt` moves to the first tab.

heh, yes, you are right. I don't know all possibilities of ranger :) May be it's not needed if you can use quantifier with gt

**Comment by mrgoodvin** [comment]
I did not tested. And yes. It is a pity that it is. In terms of performance, the code was faster.

**Comment by toonn** [comment]
The quantifier approach does some signaling to make sure the tab is loaded properly which the `tab_move` function neglects otherwise. Something to keep in mind.

**Comment by mrgoodvin** [comment]
> The quantifier approach does some signaling to make sure the tab is loaded properly which the `tab_move` function neglects otherwise. Something to keep in mind.

Thanks.

> If you specify a quantifier this already happens, for example `1gt` moves to the first tab.

This is not completely true. If the tab has been closed or moved, specifying the `1gt` quantifier will create a new tab.

**Comment by toonn** [comment]
You're right, it moves to the tab with the index you provided or opens a new one there if none exists. And 1 really means "tab named 1" not "first tab on the list."

**Pull request closed without merging**
