### PR TITLE
ext.rifle: Additional Check for mime type with mimetype command

### PR DESCRIPTION
**Pull request by mikeri**
#### ISSUE TYPE
- Breaking changes
Some MIME types are not found by rifle. With an additional test with the mimetype command after the file command returns 'application/octet-stream' rifle should now be able to recognize all known mime types in the system.

### CODE REVIEW

**Comment by toonn** [comment]
Did you handle the case where `mimetype` isn't installed?
Travis is complaining because of pylint, if you install both pylint and flake8 you can run `make test` to run the linting locally, less of a wait ; )

**Comment by mikeri** [comment]
Sorry for not testing. I corrected the indent and added a simple try except pass, it seems to work fine. Would that suffice?

**Comment by toonn** [comment]
You probably corrected the indent with the previous pylint warning. Pylint wants you to align the continuation with the opening parenthesis.
`Popen(x...` You want to have the continuing line start in the same column as `x`.

**Comment by mikeri** [comment]
Sorry again, the bare exception cause the test to fail. Added OSError, it works here with both Python2 and 3 when mimetype is not installed.

**Pull request merged**
