### PR TITLE
config.commands.cd: Add cd tab completion with less typing functionality

### PR DESCRIPTION
**Pull request by nanuda**
Finds matching directories recursively with given path string when a user presses tab key.
For example, ":cd /u/l/p<tab press>" => ":cd /usr/lib/python".

#### ISSUE TYPE

- Improvement/feature implementation

#### RUNTIME ENVIRONMENT

- Operating system and version: Linux 4.4.45
- Terminal emulator and version: gnome-terminal 3.22.1
- Python version: 2.7 and 3.6
- Ranger version/commit: 1.9.0b5
- Locale: en_US.UTF-8

#### CHECKLIST

- [X] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [X] All changes follow the code style **[REQUIRED]**
- [X] All new and existing tests pass **[REQUIRED]**
- [X] Changes require config files to be updated
    - [X] Config files have been updated
- [X] Changes require documentation to be updated
    - [X] Documentation has been updated

#### MOTIVATION AND CONTEXT

To make easier to navigate directories with cd command

#### TESTING

Ran "make test"

### CODE REVIEW

**Comment by nfnty** [comment]
Never open a new PR. Just edit and add commits to the one that is already open.

**Comment by nanuda** [comment]
ok.

**Comment by b5n** [comment]
This feature works pretty well and really useful. 

P.S.
I will be really appreciated if you fix case-insensitive after the first symbol?
For example:
cd Me<tab> => cd MEGA - doesn't work
cd ME<tab> => cd MEGA - work ok
cd me<tab> => cd MEGA - work ok
cd Rew<tab> => cd ReWrite - doesn't work
cd DO<tab> => cd Downloads - doesn't work
cd do<tab> => cd Downloads - work ok

**Comment by nanuda** [comment]
Fixing is not that hard. 
Change two lines in "[directory which ranger resides]/ranger/config/commands.py" file like below.
\--------
[Line Nr. 243: Case insensitive search for Directories]
"sub_token_contains_uc = not sub_token.islower()" to
"sub_token_contains_uc = False"

[Line Nr. 312: Case insensitive search for Bookmarks]:
"return self.process_return(start, unchanged_dest, dirs, find_bookmarks)" to
"return self.process_return(start, unchanged_dest.lower(), dirs, find_bookmarks)"
\--------

The effect of above change would be like pseudo code below
\--------
if toLowerCase([D]irectory | [B]ookmark) starts with toLowerCase(user given path), then
  include D | B as tab result.
else
  do not include D | B as tab result.
end
\--------

Half of your examples didn't work and it was the intention of mine. My assumption is "if a user presses \<shift> or \<caps> key to input one or more capital letters, then user wants case sensitive search". I can't make clear decision at this point which searching approach can fulfill more people's tastes. I'm really sorry about your inconvenience and also my broken English.

**Comment by b5n** [comment]
@nanuda Thank you very much!

**Comment by nfnty** [comment]
Could you implement the new setting `cd_tab_case`? Also fix conflicts. Thanks.

**Comment by nanuda** [comment]
done what you asked.

**Comment by nfnty** [comment]
Thanks for your work. Unfortunately this was really messy and required a complete refactor. Could you test the new implementation? Thanks.

PS. In the future always reduce nesting as much as possible and never use recursion.

**Comment by nfnty** [comment]
Have you tested the refactored implementation?

**Comment by nanuda** [comment]
Tested.

**Comment by nfnty** [comment]
Thanks!

**Pull request merged**
