### PR TITLE
Use os.copy_file_range where available to enable copy-on-write

### PR DESCRIPTION
**Pull request by ayouknowwho**
#### ISSUE TYPE
Improvement/feature implementation

#### RUNTIME ENVIRONMENT
In a VM, python 3.9.2
Locale en_GB.UTF-8
Debian Bullseye
Termit (KDE)
Latest ranger version from git with below commits

#### CHECKLIST
- [X] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [X] All changes follow the code style **[REQUIRED]**
- [X] All new and existing tests pass **[REQUIRED]**
- [X] Changes require config files to be updated
    - [X] Config files have been updated
- [X] Changes require documentation to be updated
    - [X] Documentation has been updated
- [X] Changes require tests to be updated
    - [X] Tests have been updated

#### DESCRIPTION
The implementation of file copying was not compatible with copy-on-write functionality. By using os.copy_file_range which is available in Python 3.8+ we can enable this functionality.
A new configuration setting which defaults to False enables the functionality when set to True. A check that the configuration setting is True AND the PY3 is True is performed before diverting flow to os.copy_file_range rather than using python file buffers.
CopyLoader was made SettingsAware so that the setting information can be passed down through function call parameters to copyfileobj in shutil_generatorized

#### MOTIVATION AND CONTEXT
issue https://github.com/ranger/ranger/issues/2511

#### TESTING
make test passes all tests
with the setting off a 500MB file transfer takes several seconds
with the setting on a 500MB file transfer takes less than a second

### CODE REVIEW

**Comment by ayouknowwho** [comment]
I have realised there is an additional bug that will need fixing, os.copy_file_range only works if both files are on the same filesystem, which we can't guarantee, so I do still need to enable it to fallback to the original method.

**Comment by toonn** [comment]
@ayouknowwho, can you switch the PR to "draft" until you've addressed that issue?

**Comment by ayouknowwho** [comment]
Should be able to get this done on Monday

**Comment by ayouknowwho** [comment]
I have now updated to revert to the old method in any cases where copy_file_range raises an error. I have tested on several different file system combinations successfully.

**Review by toonn — COMMENTED** [review]
I haven't found a way to check whether a file is indeed a reflinked copy of another. How can we make sure that's what's happening?

I'm somewhat coming around on making this default behavior, FYI. However, I think we'd need changes to how settings work to be able to do that.

I also realized we already have the paste symlink and hardlink commands and key mappings, so I think we should first add a key map for pasting with reflinking and then afterwards we can add a setting like implemented here. You can either open a new PR adding the binding and rebase this one afterwards or change this one. Or we can discuss further if you disagree, I'm clearly open to changing my mind on this >.<

**Comment by ayouknowwho** [comment]
There's a couple of methods that could be used to check whether something was reflinked indirectly:
A: Copying a large file on a small disk without enough space for the hard copy and see if it completes
B: Check disk usage before and after copy, ensure they are the same (works best with big file on a small disk)
I'm not sure if there's a better way, but there could well be.

There are advantages to using copy_file_range where available outside of the copy-on-write functionality, as it is all done in kernel, which supposedly offers performance benefits, and I quite like how the code works now trying this method first and falling back to the old method when we get errors.

I'm not sure about allowing the user to purposefully choose between reflinking and hard copying data, above simply enabling or disabling the functionality, what do you think the use case is for that choice being useful file-by-file? Surely you'd always want to reflink when possible and hard copy if reflinking is not available? I'm interested to hear your thoughts.

If you want to make it default behaviour I guess you can either have a disable_copy_on_write setting instead or drop the setting altogether (keeping the PY3 check I think so we aren't trying to call a function that doesn't exist)

**Comment by ayouknowwho** [comment]
I merged in the latest changes so the pull request is still up to date. There didn't seem to be any conflicts. Have you had any more thoughts on how you'd like to proceed?

**Comment by toonn** [comment]
You've convinced me that this should just be the default behavior. If it's good enough for `cp(1)` it should be good enough for us.

**Comment by iambumblehead** [comment]
cc @ayouknowwho

**Comment by ayouknowwho** [comment]
Sorry for the delayed response, I've been away on holiday, I get back later this week so I'll review properly then

**Comment by ayouknowwho** [comment]
Yes this seems like a nice simple solution, it doesn't disadvantage users in old environments heavily, since as soon as a single block fails it uses the old method from then on.

**Comment by ayouknowwho** [comment]
As far as I was aware it was ready to be merged.

**Comment by toonn** [comment]
I still haven't found a good way to verify the files created are really reflinks. But I'm taking @ayouknowwho's last comments as approval of my changes so I'm going ahead and merging. Release the Kraken^Wcopy-on-write behavior!

**Pull request merged**
