### PR TITLE
small_features™

### PR DESCRIPTION
**Pull request by eMPee584**
RFC..
Note: there are really awkward file extensions around.. like **.R.rkward_autosave** :open_mouth: 
`os.path.splitext` handles them quite nicely.. but is it ok there?

### CODE REVIEW

**Comment by hut** [comment]
The file extension cut-off patch works well =D
But the -x patch is missing some things:
* documentation
* integration with rifle (ranger/ext/rifle.py), since the flags in :shell and in rifle.conf should be kept consistently.

**Comment by eMPee584** [comment]
..what about the file extension cut-off thang? Is there anything you want to see changed?

**Comment by hut** [comment]
No, it's perfectly fine. :)

You just made it more complicated for me by putting multiple things in 1 pull request, so I had to `git cherry-pick` and couldn't do a simple merge. I guess that this little bit of extra work made me procrastinate it for so long. I'm not complaining though, thank you for the patches. :)

**Comment by hut** [comment]
So, everything except the -x flag patch is merged now

**Comment by nfnty** [comment]
Rebase this PR and make sure that all tests pass. See the updated `CONTRIBUTING` and `HACKING` documents for more info. Thanks!

**Comment by eMPee584** [comment]
ok, sometime this week :+1:

**Comment by nfnty** [comment]
@eMPee584 When is it going to be ready?

**Comment by eMPee584** [comment]
wow time flies. :hourglass: 
just looking into it.. uhm how do I run ranger from my source checkout, ignoring the older globally installed copy?

**Comment by nfnty** [comment]
`python ranger.py`

**Comment by eMPee584** [comment]
why doesn't that work when giving the full path `python /usr/src/repositories/ranger/ranger.py` :thinking:

**Comment by nfnty** [comment]
What do you mean by "doesn't work"?

**Comment by eMPee584** [comment]
well with an absolute path given, it does invoke the system version of ranger instead.
but well yeah sorted.

**Comment by nfnty** [comment]
Strange, can't reproduce that issue.

**Comment by eMPee584** [comment]
hhm
I might check with fatrace later what is going on..

**Comment by eMPee584** [comment]
well I don't know why, but indeed `python /usr/src/repositories/ranger/ranger.py` doesn't work here.
```
python(19817): O /usr/src/repositories/ranger/ranger.py
python(19817): R /usr/src/repositories/ranger/ranger.py
python(19817): C /usr/src/repositories/ranger/ranger.py
python(19817): RO /usr/src/repositories/ranger/ranger.py
python(19817): R /usr/src/repositories/ranger/ranger.py
python(19817): C /usr/src/repositories/ranger/ranger.py
python(19817): O /usr/lib/python2.7/dist-packages/ranger/__init__.py
python(19817): RO /usr/lib/python2.7/dist-packages/ranger/__init__.pyc
python(19817): C /usr/lib/python2.7/dist-packages/ranger/__init__.pyc
python(19817): O /usr/lib/python2.7/dist-packages/ranger/core/__init__.py
python(19817): O /usr/lib/python2.7/dist-packages/ranger/core/__init__.pyc
python(19817): RC /usr/lib/python2.7/dist-packages/ranger/core/__init__.pyc
python(19817): C /usr/lib/python2.7/dist-packages/ranger/core/__init__.py
python(19817): O /usr/lib/python2.7/dist-packages/ranger/core/main.py
python(19817): O /usr/lib/python2.7/dist-packages/ranger/core/main.pyc

```
well — wha'eva.

**Comment by eMPee584** [comment]
Upon further review of that -x flag, I think it's not worth adding. I never actually used it, using a tmux construct instead. And screen fans righteously would demand their own flag.

**Pull request closed without merging**
