### PR TITLE
Fix the Kitty previews in fullscreen mode

### LINKED ISSUE #1431: Kitty previews don't cleanup after themselves in fullscreen mode
#### Runtime Environment

- Operating system and version: Gentoo Linux
- Terminal emulator and version: Kitty
- Python version: 3.6.5
- Ranger version/commit: e06e12ef
- Locale: en_US.utf8

#### Current Behavior

With `preview_images_method` set to `kitty`, when I fullscreen the image preview with <kbd>i</kbd> and then press <kbd>i</kbd> again, the display gets screwed up. Specifically the file listing gets shown below the space that used to be occupied by the image. Pressing <kbd>Ctrl+L</kbd> fixes it. @toonn mentioned that it happens only when the file listing is shorter than the whole terminal height.

#### Expected Behavior

Kitty previews should work in fullscreen without breaking the rest of ranger.

#### Possible Solutions

Refresh the display after clearing the Kitty preview. Fix is on the way already.

#### Steps to reproduce
1. `:set preview_images_method kitty`
2. <kbd>z</kbd><kbd>i</kbd>
3. Focus an image in a directory with not too many files.
4. <kbd>i</kbd><kbd>i</kbd>

### PR DESCRIPTION
**Pull request by Vifon**
Fixes #1431.

### CODE REVIEW

**Comment by mark-dawn** [comment]
I was back in my hometown without a *nix machine for some time, sorry.
I tried replicating this in various terminal sizes and file listing lengths but to no avail.
I will try to see if I can see something outside my dev branch, maybe I did something weird in it.
At least we have a working fix for people experiencing the issue.

**Comment by toonn** [comment]
@mark-dawn, note that the issue I mentioned you for is *different* from the one this PR fixes.

**Comment by mark-dawn** [comment]
I don't get the flickering either, I should have made that clearer.
I can get a single slow "flicker" by pressing any input while the fullscreen preview is active, but only _once_. Nothing continuous thought.

**Comment by toonn** [comment]
It's intermittent for me so it's probably hard to debug.

**Pull request merged**
