### PR TITLE
Added Zenburn color scheme

### PR DESCRIPTION
**Pull request by alex3kov**
See https://gist.github.com/ivoarch/8249238. Props to Ivaylo Kuzev.

#### ISSUE TYPE
- Improvement/feature implementation

#### RUNTIME ENVIRONMENT
- Operating system and version: 
Arch LInux
- Terminal emulator and version: 
termite v13  
- Python version: 
Python version: 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]
- Ranger version/commit: 
ranger version: ranger-master 1.9.1
- Locale: 
Locale: en_GB.UTF-8

#### CHECKLIST

- [x] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [x] All changes follow the code style **[REQUIRED]**
- [x] All new and existing tests pass **[REQUIRED]**
- [?] Changes require config files to be updated
    - [ ] Config files have been updated
- [ ] Changes require documentation to be updated
    - [ ] Documentation has been updated
- [ ] Changes require tests to be updated
    - [ ] Tests have been updated

#### DESCRIPTION

Zenburn color scheme.

#### TESTING

Running ranger with this color scheme.

### CODE REVIEW

**Comment by toonn** [comment]
I'd be ok with merging this if you fix all the linting issues. We should add both solarized and this to the documentation probably.

Or maybe we should make another repository under the ranger project that collects colorschemes?

**Comment by toonn** [comment]
@ivoarch, vifon pointed out that as the copyright owner we should ask you for permission to redistribute the colorscheme under the GPLv3.

We would be adding it in a seperate colorschemes repo but under the same license to avoid any issues with redistributing it with ranger.

**Comment by Vifon** [comment]
@toonn, no, no, that's not what I meant. That's important too but I meant asking @ivoarch / Ivaylo Kuzev for permission, as the theme author.

**Comment by Vifon** [comment]
Or... yes, that is what I meant. At the glance I though you asked @alex3kov. Sorry for the confusion.

**Comment by alex3kov** [comment]
@toonn 
> Or maybe we should make another repository under the ranger project that collects colorschemes?  

[base16](https://github.com/chriskempson/base16)-ranger perhaps?

**Comment by toonn** [comment]
Isn't base16 too specific, I was just gonna call it colorschemes.

**Comment by alex3kov** [comment]
@toonn 
> Isn't base16 too specific, I was just gonna call it colorschemes.  

Take a look at base16 repo. It's like a framework for generating a lot of different themes for a given app once you code the template right. I'm not sure how tricky it would get for ranger with Python theme files.

**Comment by toonn** [comment]
I've seen base16, it's still just 1 family of themes, no need to limit the scope of our colorschemes repo to only 16 color themes. Most terminals have 256 available, let's go crazy ; )

**Comment by alex3kov** [comment]
@toonn 
> no need to limit the scope of our colorschemes repo to only 16 color themes.  

It is not at all limited to 16 themes, take a look here for example: https://github.com/khamer/base16-i3/tree/master/themes  
Getting back to this PR: I fixed the linting. `test make` now gives only 2 errors about `if` branches - not sure how to avoid them. Will you merge it in present state?

**Comment by toonn** [comment]
The base16 project explicitly states this:

> An architecture for building themes based on carefully chosen syntax highlighting using a base of sixteen colours.

Not sure why you think base16 would be a better name than colorschemes tbh, there could still be a base16 subdirectory in the repo.

You can add this comment on the function definition to get rid of those last two warnings: `# pylint: disable=too-many-branches,too-many-statements`.

The linting issues aren't really what's holding back the merge. We're waiting for explicit permission from @ivoarch.

**Comment by hut** [comment]
How was @ivoarch contacted so far? Just via mentioning him in the github comments? He doesn't seem very active on github. If nobody has done it so far, maybe we should rather write him an email.

**Comment by toonn** [comment]
I'll send an email.

**Comment by toonn** [comment]
Actually, I just noticed the file still claims @hut has copyright. Since it's based on our default colorscheme it's GPLv3 already. So let's just go ahead with the colorschemes repo.

**Comment by ivoarch** [comment]
Hi, I'm sorry for taking so long to answer. You can redistribute the colorscheme under the license you want. The colorscheme is based on the ranger default theme. Cheers!

**Comment by toonn** [comment]
I created the repo and added `zenburn.py` here: https://github.com/ranger/colorschemes/pull/1

Thanks for the work, @alex3kov, and thanks for the original theme, @ivoarch!

**Pull request closed without merging**
