### PR TITLE
Added except catching when previewing files in Python2

### PR DESCRIPTION
**Pull request by chronzerg**
#### ISSUE TYPE

- Bug fix

#### RUNTIME ENVIRONMENT

- Operating system and version: macOS 10.13.2
- Terminal emulator and version: Terminal 2.8
- Python version: 2.7.14
- Ranger version/commit: ranger-master 1.9.0b6
- Locale: None.None

#### CHECKLIST

- [x] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [x] All changes follow the code style **[REQUIRED]**
- [x] All new and existing tests pass **[REQUIRED]**
- [ ] Changes require config files to be updated
    - [ ] Config files have been updated
- [ ] Changes require documentation to be updated
    - [ ] Documentation has been updated
- [ ] Changes require tests to be updated
    - [ ] Tests have been updated

#### DESCRIPTION

When reading a file for which Ranger doesn't have permissions, Python3
throws an OSError. Python2 on the other hand throws a IOError, which
wasn't being caught and caused Ranger to crash. IOError was added to
catch statements for this reason.

#### MOTIVATION AND CONTEXT

This changes fixes the problems outlined in issue #1033.

#### TESTING

The tests run by `make test` were run and pass.

### CODE REVIEW

**Comment by toonn** [comment]
Did you check all the sites where an `OSError` is currently caught? Looks to me like there's a bunch more suspicious ones, like in `ranger/container/tags.py`. I feel like this PR would be a good place to go over all of them.

**Comment by toonn** [comment]
I'd also like to see an explicit check on the version since the catch clauses swallow all those exceptions silently.

**Comment by chronzerg** [comment]
@toonn Are you saying to check the version of Python in the `catch` block and rethrow if we caught the wrong exception for said version?

```python
except (OSError):
    if sys.version_info[0] < 3:
        raise
except (IOError):
    if sys.version_info[0] >= 3:
        raise
```

**Comment by toonn** [comment]
I was thinking about it the other way round but that's probably more convenient yes.

**Pull request merged**
