### PR TITLE
Boldisnotbright

### PR DESCRIPTION
**Pull request by toonn**
Stop lying and use bright instead of bold. Fall back to dim white instead of bright black in terminals that don't support bright colors.

### CODE REVIEW

**Comment by Vifon** [comment]
Is it supposed to merge the draw borders PR too?

**Comment by toonn** [comment]
No, I don't think it is. That's probably why the list of commits is so screwy? I based it off the wrong branch? I'll rebase I guess.

**Comment by Vifon** [comment]
This way we won't have any differentiation between bold/bright and regular text on a terminal with no bright colors, correct? If that was your intention and you tested it's not a true problem, merge away.

**Comment by toonn** [comment]
Yes, I don't really like it. BUT afaik that would've been the case with the current code too? Since bold is usually implemented as bright.

You should check out the PR so you can judge the colors. I'd like more contrast tbh but I"m not sure that's possible. I'm currently thinking of adding the bright instead of replacing the bold. Because in terminals that *do* support it it does make the difference clearer imo. But I'm not sure what'll happen in terminals that support bold as bright? Would we get out of range of the available colors?

One nice improvement that comes with this though now marked and marked & cut files *do* look different which didn't use to be the case, at least for me.

**Pull request merged**
