### PR TITLE
[WIP] Add support for modifier combos + arrow keys

### PR DESCRIPTION
**Pull request by Enzime**
Currently works in termite, but not working in urxvt.
#574

### CODE REVIEW

**Comment by Enzime** [comment]
Now supports urxvt :)

**Comment by nfnty** [comment]
Rebase this PR and make sure that all tests pass. See the updated `CONTRIBUTING` and `HACKING` documents for more info. Thanks!

**Comment by nfnty** [comment]
Potentially also solves #266.

**Comment by nfnty** [comment]
This is very hackish and will break easily. We should be looking into using something like [libtickit](http://www.leonerd.org.uk/code/libtickit/) instead.

**Comment by nfnty** [comment]
This will need a lot of work to implement in a general way. Continue discussion in #574.

**Pull request closed without merging**
