### PR TITLE
improving! implementing moving command to first and last tabs

### PR DESCRIPTION
**Pull request by mrgoodvin**
improving allows to move to first and last tab fastly
tab_move 1000 #last
tab_move -1000 #fist

#### ISSUE TYPE

- Improvement/feature implementation

#### RUNTIME ENVIRONMENT

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
- Locale: 

#### CHECKLIST

- [X] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [X] All changes follow the code style **[REQUIRED]**
- [X] All new and existing tests pass **[REQUIRED]**
- [X] Changes require config files to be updated
    - [ ] Config files have been updated
- [X] Changes require documentation to be updated
    - [ ] Documentation has been updated
- [X] Changes require tests to be updated
    - [ ] Tests have been updated

#### DESCRIPTION

improve tab_move method in actions.py.
arg offset is must been big number (>> tab counts)

#### MOTIVATION AND CONTEXT

optionly improv a navigation

speed tabs moving

### CODE REVIEW

**Comment by toonn** [comment]
Looks to me like you're breaking the cyclic nature of moving among tabs? Why?
Again, this is vim behavior.

**Comment by mrgoodvin** [comment]
No I do not do it. This idea (moving last and end) wiil by not work if table are gretting 1000 :). Its not possible. If is true even tabs=1001, cyclic worked to will be, but do not moving last and first. Ok.

**Comment by mrgoodvin** [comment]
It is comfortably to me

**Comment by toonn** [comment]
I'm having trouble understanding your description. Are you saying that `:tab_move` doesn't work with large numbers?

**Comment by mrgoodvin** [comment]
Do not will be worked move to first and last tab only. And not worket it only if arg abs(defaul 1000, -1000) < (counts of tab). Whos will be open 1000-th tab? I know it, nobody do it:)

**Pull request closed without merging**
