### PR TITLE
Fix ranger not opening in chrome, chromium on Ubuntu.

### PR DESCRIPTION
**Pull request by 2E0PGS**
Allows Ubuntu users to open in google-chrome and chromium-browser packages.

#### ISSUE TYPE

- Improvement/feature implementation

#### RUNTIME ENVIRONMENT

- Operating system and version: Ubuntu 16.04
- Terminal emulator and version: Terminator
- Python version: Python 2.7.12, Python 3.5.2
- Ranger version/commit: ranger-stable 1.7.1
- Locale: en_GB

#### CHECKLIST

- [ x ] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [ x ] All changes follow the code style **[REQUIRED]**
- [ x ] All new and existing tests pass **[REQUIRED]**
- [ 0 ] Changes require config files to be updated 
    - [ x ] Config files have been updated
- [ 0 ] Changes require documentation to be updated
    - [ 0 ] Documentation has been updated
- [ 0 ] Changes require tests to be updated
    - [ 0 ] Tests have been updated

#### DESCRIPTION

Modified the `rifle.conf` and added `has google-chrome` and `has chromium-browser` then adjusted the spacing to adjust for new longer `has chromium-browser` line.
This allows Ubuntu users to open in google-chrome and chromium-browser packages.

#### MOTIVATION AND CONTEXT

I run `chromium-browser` on Ubuntu and it's package is not called `chromium` like on Arch Linux.

#### TESTING

Just a config change. Have tested both `google-chrome` and `chromium-browser` they both open fine.

### CODE REVIEW

**Comment by Vifon** [comment]
Good idea, thanks!

Consider moving `google-chrome` below `chromium` and `chromium-browser`. If the user has both installed, it's likely they use Chromium as their main browser and Google Chrome for some things specific to the proprietary components of Google Chrome. At least that's the most likely scenario I see. What do you think about it?

**Comment by 2E0PGS** [comment]
Yes however I know many Linux distros that come with chromium. I can't think of any that come with google-chrome. So I was following the current code comments that suggest we prioritize user installed browsers.

**Comment by 2E0PGS** [comment]
Just change the code to match your suggestion: @Vifon b1e08bf5b52746da2f0e5d9995e8dbc8c8505f62

**Comment by Vifon** [comment]
Sorry for the delay. Looks fine (as a matter of fact, your previous reasoning was fine too), I'll merge it in a minute. Thank you! :)

**Comment by 2E0PGS** [comment]
No problem. Thanks for the merge! Cheers!

**Pull request merged**
